Add refresh option to recent transaction activity.
MatthijsKok/TI2806-Contextproject pull request #119
Opened 2017-05-19 14:23 UTC by Ishadijcks

Fancy pulldown to refresh added to recent transaction activity.

2017-05-19 14:28 UTC, joskuijpers requested changes

2017-05-19 14:28 UTC, joskuijpers commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +
Too many newlines

2017-05-19 14:28 UTC, joskuijpers commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +        SwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
Try to use a lambda here.

```java
SwipeRefreshLayout.setOnRefreshListener(() -> retrieveRecentTransactions())
```

2017-05-19 14:32 UTC, Ishadijcks commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +        SwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
Done

2017-05-19 14:32 UTC, Ishadijcks commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +
Done

2017-05-22 07:44 UTC, joskuijpers approved these changes

2017-05-22 07:47 UTC, merged