Feature/postpayment
MatthijsKok/TI2806-Contextproject pull request #129
Opened 2017-05-25 12:48 UTC by RvdK

Allows you to create add a transaction to the bunq account

2017-05-25 16:16 UTC, joskuijpers commented
Could you rebase on develop and push? Then travis should be nicer.

2017-05-26 08:48 UTC, RvdK commented
rebase did not help

2017-05-26 09:43 UTC, joskuijpers commented
Rebase again, after the develop build finished. It should work... (it must :'( )

2017-05-26 10:55 UTC, RvdK commented
merged the extended testing with this pr as they are related

2017-05-29 07:29 UTC, joskuijpers approved these changes

2017-05-29 07:45 UTC, MatthijsKok requested changes
Some additional changes. code is a good addition.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        CompletableFuture<Void> future;
Unused, please remove. Please think about putting other variables in BeforeClass or Before methods to remove a lot of boilerplate.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        CompletableFuture<Void> future;
Unused, please remove.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        CompletableFuture<Void> future;
Unused, please remove.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        CompletableFuture<Void> future;
Unused, please remove.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +
Again, please check your staged files and changes before committing. This is easily avoidable. Please revert

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/activities/RecentTransactionsActivity.java
> +
Please revert.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +    public void testGetUsers() throws ExecutionException, InterruptedException {
Please also add tests for bad code paths and any exceptions that might be thrown.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        assertTrue(bank.sendTransaction(pay).get());
Please also test that the balances are changed, the transaction shows up when you get the transaction list, etc...

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        Transaction t = transactions.get(transactions.size() - 2);
Please test that multiple transactions exist, since it is a list.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +    public void testListTransactions() throws ExecutionException, InterruptedException {
Please also add a test that returns an empty list.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +    public void testGetAccounts() throws ExecutionException, InterruptedException {
Please test that multiple accounts exist, since it is a list. Also add a test for empty list etc..

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        BunqTransaction tran = (BunqTransaction) transaction;
please check instanceof before casting.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        return future.thenApply((PaymentService.PostResponse response) -> {
Please change PaymentService.PostResponse into an import.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTransaction.java
> +    public BunqTransaction(PaymentService.ListResponse.Payment payment, Account account) {
Please change PaymentService.ListReponse.Payment into an import.

2017-05-29 07:45 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTransaction.java
> +    public PaymentService.PostRequest convertToRequest() {
Please change PaymentService.PostRequest into an import, and others below as well.

2017-05-29 07:50 UTC, RvdK commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        assertTrue(bank.sendTransaction(pay).get());
I do not agree because bunq approves the transaction when returning true which is enough

2017-05-29 07:50 UTC, joskuijpers commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        return future.thenApply((PaymentService.PostResponse response) -> {
Don't, as PostResponse is not a unique class name: it is an inner name of any API that has a post response object. It is also not clear when reading the code what "PostResponse" refers to: it is now.

2017-05-29 07:50 UTC, joskuijpers commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTransaction.java
> +    public BunqTransaction(PaymentService.ListResponse.Payment payment, Account account) {
Again, see previous comment

2017-05-29 07:51 UTC, joskuijpers commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTransaction.java
> +    public PaymentService.PostRequest convertToRequest() {
Again, don't. See previous comments.

2017-05-29 07:59 UTC, RvdK commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTransaction.java
> +    public PaymentService.PostRequest convertToRequest() {
Disagree we have many post requests (posssibly for each service) and that would decrease readablialty

2017-05-29 08:00 UTC, joskuijpers commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +        Transaction t = transactions.get(transactions.size() - 2);
The list size constantly changes and can't be independently verified. Only thing that can be done is that the size is at least 3. But if that is not the case, get() will throw an exception and thus also fail the test.

2017-05-29 08:01 UTC, RvdK commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        BunqTransaction tran = (BunqTransaction) transaction;
instance of is noet needed here since transaction is extended by bunqtransaction so this will always succeed

2017-05-29 08:09 UTC, RvdK commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +    public void testGetAccounts() throws ExecutionException, InterruptedException {
We can't this is a live test and we can not add accounts

2017-05-29 08:33 UTC, MatthijsKok commented on BankChain/app/src/androidTest/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqTest.java
> +    public void testGetUsers() throws ExecutionException, InterruptedException {
We agreed to not test any bad code paths, since we are measured by line coverage instead of branch coverage.

2017-05-29 08:34 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        BunqTransaction tran = (BunqTransaction) transaction;
Agreed.

2017-05-29 08:35 UTC, MatthijsKok commented on BankChain/app/src/main/java/nl/tudelft/ewi/ds/bankchain/bank/bunq/BunqBank.java
> +        return future.thenApply((PaymentService.PostResponse response) -> {
Agreed.

2017-05-29 09:07 UTC, MatthijsKok approved these changes
LGTM with changes

2017-05-29 12:35 UTC, merged